name: 'Terraform CI/CD'

on:
  push:
    branches:
      - infrastructure
  pull_request:
    branches:
      - infrastructure

env:
  TF_VERSION: '1.5.0'

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: write

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Google Cloud Authentication'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: 'Configure GCP Project'
        run: gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: 'Terraform Init'
        run: |
          terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
          TF_VAR_region: "us-central1"  # Replace with your desired region
          TF_VAR_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_gke_node_count: 3       # Replace with desired node count
          TF_VAR_gke_machine_type: "e2-medium" # Replace with desired machine type
          TF_VAR_gke_master_version: "latest"  # Replace with desired GKE version
        working-directory: infrastructure

      - name: 'Terraform Plan'
        run: |
          terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
          TF_VAR_region: "us-central1"
          TF_VAR_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_gke_node_count: 3
          TF_VAR_gke_machine_type: "e2-medium"
          TF_VAR_gke_master_version: "latest"
        working-directory: infrastructure

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/infrastructure'
        run: |
          terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
          TF_VAR_region: "us-central1"
          TF_VAR_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_gke_node_count: 3
          TF_VAR_gke_machine_type: "e2-medium"
          TF_VAR_gke_master_version: "latest"
        working-directory: infrastructure
